name: Sync Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master

    - name: Sync with S3
      uses: mirrorweb/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_GHA_ROLE: ${{ secrets.AWS_GHA_ROLE }}
        SOURCE_DIR: './website'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


